### ISSUE TITLE
Expose v-bind functionality in a more ergonomic way

### ISSUE THREAD

**Issue by jamesnvc** [swi-prologhackday/vuelog#1]
i.e. to make a css class be conditionally applied, the current solution is to do something like

```prolog
label(['v-bind:class'('{class: item.complete}')], ...)
```
it would be nice if we could express this in a more prolog-y way, the same way we handle `v-for` and template things.

**Comment by Anniepoo** [comment]
What about tossing the whole thing in a quasiquoter? The syntax of the quasiquoter could be whatever semi-html you wanted.

html({|vue(SomeVar)||     ... termerized html with special vue stuff ...  |}

**Comment by jamesnvc** [comment]
Current approach I'm trying out is using `@` to make the thing inside it "bound"; e.g. if the plain v-bind looks like this:

```prolog
label('v-bind:class'(active('item.activated')), ...)
```

then with the stuff added by 2b4208a3c044806ad179c4584e2219c9f2220fd6, it can be re-written as

```prolog
label(@(class(active='item.complete')), ...)
```
